In [1]:
import numpy as np

In [2]:
# 1.Задати вектор з 5 натуральних чисел
vector = np.array([1, 2, 3, 4, 5])
print(vector)

[1 2 3 4 5]


In [3]:
# 2. Транспонувати вектор
v1 = np.matrix([1, 2, 3, 4, 5])
print(v1)

v2 = v1.T
print(v2)


[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [5]:
# 3.Напишіть функцію, яка перевертає вектор у зворотньому порядку 
v = np.array([1, 2, 3, 4, 5])
print( v[::-1])

[5 4 3 2 1]


In [6]:
v = np.flip(v)
print(v)

[5 4 3 2 1]


In [7]:
# 4.Знайти середнє значення вектора
print(np.mean(v))

3.0


In [8]:
# 5. Знайти найбільший і найменший елементи вектора
print(np.max(v))
print(np.min(v))

5
1


In [9]:
# 6. Обчислити скалярний добуток (dot product) двох векторів
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(np.dot(v1, v2))
print(v1 * v2)

32
[ 4 10 18]


In [11]:
# 7. Написати функцію, яка нормалізує вектор (зводить до одиничної довжини)
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)

print(norm)

v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

In [12]:
# 8. Задайте два вектори. Визначте, чи є вони ортогональними. Підказка: якщо скалярний добуток дорівнює нулю, вектори ортогональні.
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])

np.dot(v1, v2)

np.int64(0)


np.int64(0)

In [13]:
# 9. Визначте унікальні елементи вектора
v = np.array([1, 2, 3, 2, 2, 4, 5, 3])
np.unique(v)

array([1, 2, 3, 4, 5])

In [14]:
# 10. Знайти вектори

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1 - v2)
print(v2 - v1)
print(v1 + v2)
print(v2 + v1)
print(v1 * v2)
print(v2 * v1)
print(v1 / v2)
print(v2 / v1)


[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


In [16]:
#11. Перевірити, чи дорівнює довжина вектора 5
vector = np.array([1,2,3,4,5])
length = np.linalg.norm(vector)

np.isclose(length, 5)

np.False_

In [17]:
# 12. Задати матрицю, заповнену випадковими числами
a = np.random.randint(0, 11, (3, 3))
print(a)

[[9 4 8]
 [1 5 1]
 [6 9 7]]


In [18]:
# 13. Обчислити визначник матриці
np.linalg.det(a)

np.float64(62.00000000000001)

In [19]:
# 14. Знаходження оберненої матриці
np.linalg.inv(a)


array([[ 0.41935484,  0.70967742, -0.58064516],
       [-0.01612903,  0.24193548, -0.01612903],
       [-0.33870968, -0.91935484,  0.66129032]])

In [20]:
# 15. Розв'язок системи лінійних рівнянь A:x = b, де A — матриця коефіцієнтів, b — вектор вільних членів.

a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])  
b = np.array([5, 3, 4])  

x = np.linalg.solve(a, b) 
print(x)
# Альтернативний метод
inv_a = np.linalg.inv(a) 
x1 = inv_a.dot(b)  
print(x1)

[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]


In [21]:
# 16. Множення двох матриць
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]]) 
b = np.array([5, 3, 4])  

np.dot(a, b)  

array([-2, -6, 16])

In [22]:
a = np.matrix([[1, 3, -4], [0, 2, -3]])
b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])
print(a)
print(b)
print(np.dot(a, b))

[[ 1  3 -4]
 [ 0  2 -3]]
[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[-1  4  7]
 [-5  0  1]]


In [25]:
# 17. Транспонування матриці
print(a.T)
print(b.T)

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


In [26]:
print(np.transpose(a))
print(np.transpose(b))

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


In [27]:
# 18. Перевірка симетричності матриці
matrix = np.matrix([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
np.allclose(matrix, matrix.T)

True

In [28]:
# 19. Обчислення сліду матриці
np.trace(matrix)

np.int32(6)

In [29]:
# 20. Дії з матрицями
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[5, 6], [7, 8]])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [33]:
# 21. Піднесення матриці до ступеня 
a = np.matrix([[1, 2], [3, 4]])
np.linalg.matrix_power(a, 2)

matrix([[ 7, 10],
        [15, 22]])

In [30]:
# 22. Сортування рядків та стовпців в матриці
b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])
print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [31]:
a = np.array([[1, 4], [3, 1]])
print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]


In [32]:
# 23. Підраховуємо суму елементів кожного рядка матриці та перетворюємо результат у вектор-стовпчик
row_sums = np.sum(a, axis=1).reshape(-1, 1)
print("Сума елементів кожного рядка:")
print(row_sums)

Сума елементів кожного рядка:
[[5]
 [4]]
