In [2]:
import numpy as np
print(np.__version__)

2.3.1


In [7]:
# 1. Створи матрицю 3*3, заповни її цілими випадковими числами від 1 до 5
matrix = np.random.randint(1, 6, size=(3,3))
print(matrix)

[[2 1 2]
 [2 5 5]
 [3 5 3]]


In [8]:
# 2. Обчислити визначник матриці
det = np.linalg.det(matrix)
print(det)

-21.0


In [9]:
# 3. Знайти добуток всіх елементів матриці 
product = np.prod(matrix)
print(product)

9000


In [10]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
print(prod_1*prod_2*prod_3)

9000


In [11]:
# 4.Знайти суму всіх елементів матриці 
sum = np.sum(matrix)
print(sum)

28


In [12]:
# 5. Обчислити найбільший та найменший елементи матриці
max_element = np.max(matrix)
min_element = np.min(matrix)
print("Найбільший елемент матриці: ", max_element)
print("Найменший елемент матриці: ", min_element)

Найбільший елемент матриці:  5
Найменший елемент матриці:  1


In [13]:
# 6. Знайти середнє значення елементів матриці
mean = np.mean(matrix)
print("Cереднє значення елементів матриці: ", mean)

Cереднє значення елементів матриці:  3.111111111111111


In [14]:
# 7. Знайти матрицію яка складена з квадаратних коренів 
sqrt_matrix = np.sqrt(matrix)
print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[1.41421356 1.         1.41421356]
 [1.41421356 2.23606798 2.23606798]
 [1.73205081 2.23606798 1.73205081]]


In [15]:
# 8. Обчислшити суму елементів кожного рядку.Записати як вектор-стовпчик
row_sums = np.sum(matrix, axis = 1).reshape(-1,1) 
print("Сума елементів кожного рядка:")
print(row_sums)

Сума елементів кожного рядка:
[[ 5]
 [12]
 [11]]


In [16]:
# 9. Створити вектор, що містить 25 елементів. Заповни числами від 0 до 9. Відсортувати числа за спаданням.
vector = np.random.randint(0,10,size = 25)
print("Початковий вектор:")
print(vector)

sorted_vector = np.sort(vector)[::-1]
print("Вектор після сортування за спаданням: ")
print(sorted_vector)

Початковий вектор:
[1 7 2 1 4 8 2 3 4 5 7 7 9 0 8 3 7 0 0 8 6 7 9 8 2]
Вектор після сортування за спаданням: 
[9 9 8 8 8 8 7 7 7 7 7 6 5 4 4 3 3 2 2 2 1 1 0 0 0]


In [17]:
# 10. Знайти моду, медіану, середнє, максимальне та мінімальне значення вектора
from scipy import stats

# Створюємо випадковий вектор від 0 до 9
vector = np.random.randint(0, 10, size=25)
print("Вектор:", vector)

# Знаходимо моду
mode = stats.mode(vector, keepdims=True)

# Знаходимо медіану
median = np.median(vector)

# Знаходимо середнє
mean = np.mean(vector)

# Знаходимо максимальне значення
max_value = np.max(vector)

# Знаходимо мінімальне значення
min_value = np.min(vector)

print("Мода:", mode.mode[0])
print("Медіана:", median)
print("Середнє:", mean)
print("Максимальне значення:", max_value)
print("Мінімальне значення:", min_value)

Вектор: [4 2 3 0 9 7 3 8 4 7 1 6 5 5 6 9 9 7 8 5 4 7 5 4 2]
Мода: 4
Медіана: 5.0
Середнє: 5.2
Максимальне значення: 9
Мінімальне значення: 0


In [19]:
# 11. Створити дві матриці 4*4 заповнені числами від 1 до 10. Обчислити суму,різницю, добуток та частку.
matrix1 = np.random.randint(1, 11, size=(4,4))
matrix2 = np.random.randint(1, 11, size=(4,4))
print("Матриця 1: ")
print(matrix1)
print("Матриця 2: ")
print(matrix2)
# Обчислюємо суму матриць
matrix_sum = matrix1 + matrix2

# Обчислюємо різницю матриць
matrix_diff = matrix1 - matrix2

# Обчислюємо поелементний добуток матриць
matrix_product = matrix1 * matrix2

# Обчислюємо поелементну частку матриць
matrix_division = np.divide(matrix1, matrix2, where=(matrix2 != 0))

print("\nСума матриць:")
print(matrix_sum)

print("\nРізниця матриць:")
print(matrix_diff)

print("\nПоелементний добуток матриць:")
print(matrix_product)

print("\nПоелементна частка матриць:")
print(matrix_division)

Матриця 1: 
[[ 3  3  2  3]
 [ 5  5  4  1]
 [ 9 10  7  7]
 [ 3  4  1  2]]
Матриця 2: 
[[ 5  7 10  9]
 [10  4  5  7]
 [ 6  7  2  6]
 [ 4  7  9 10]]

Сума матриць:
[[ 8 10 12 12]
 [15  9  9  8]
 [15 17  9 13]
 [ 7 11 10 12]]

Різниця матриць:
[[-2 -4 -8 -6]
 [-5  1 -1 -6]
 [ 3  3  5  1]
 [-1 -3 -8 -8]]

Поелементний добуток матриць:
[[15 21 20 27]
 [50 20 20  7]
 [54 70 14 42]
 [12 28  9 20]]

Поелементна частка матриць:
[[0.6        0.42857143 0.2        0.33333333]
 [0.5        1.25       0.8        0.14285714]
 [1.5        1.42857143 3.5        1.16666667]
 [0.75       0.57142857 0.11111111 0.2       ]]


In [ ]:
"""
Висновок:
У ході виконання лабораторної роботи було використано веб-середовище Jupyter Notebook, а саме середовище з інтегрованим інтерпретатором Python 3.13
та бібліотеками NumPy і SciPy. Ми застосовували наші знання з лінійної алгебри для вирішення елементарних задач, а саме: працювали з матрицями 
та векторами, виконуючи над ними арифметичні та статистичні операції. Робота продемонструвала ефективність NumPy у математичних розрахунках, 
а також дала підгрунтя для подальшого вивчення машинного навчання.
"""